apiVersion: v1
data:
  policy.csv: |
    g, admin, role:owner
    g, operator, role:operator
    g, viewer, role:viewer
    p, role:owner, applications, *, */*, allow
    p, role:owner, clusters, *, *, allow
    p, role:owner, repositories, *, *, allow
    p, role:owner, projects, *, *, allow
    p, role:owner, accounts, *, *, allow
    p, role:owner, gpgkeys, *, *, allow
    p, role:owner, logs, *, *, allow
    p, role:owner, exec, *, *, allow
    p, role:operator, applications, get, */*, allow
    p, role:operator, applications, list, */*, allow
    p, role:operator, applications, watch, */*, allow
    p, role:operator, applications, sync, */*, allow
    p, role:operator, applications, action/*, */*, allow
    p, role:operator, logs, get, */*, allow
    p, role:operator, applications, *, test-apps/*, allow
    p, role:operator, applications, update/*, */*, allow
    p, role:operator, applications, delete/*, */*, allow
    p, role:viewer, applications, get, */*, allow
    p, role:viewer, applications, list, */*, allow
    p, role:viewer, applications, watch, */*, allow
    p, role:viewer, clusters, get, *, allow
    p, role:viewer, repositories, get, *, allow
    p, role:viewer, projects, get, *, allow
    p, role:readonly, applications, get, */*, allow
    p, role:readonly, applications, list, */*, allow
  policy.default: role:readonly
  scopes: '[groups]'
kind: ConfigMap
metadata:
  annotations:
    argocd.version: v2.14.2
    demo.upgrade.step: v2.10-to-v2.14
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"policy.csv":"g, admin, role:owner\ng, operator, role:operator\ng, viewer, role:viewer\np, role:owner, applications, *, */*, allow\np, role:owner, clusters, *, *, allow\np, role:owner, repositories, *, *, allow\np, role:owner, projects, *, *, allow\np, role:owner, accounts, *, *, allow\np, role:owner, gpgkeys, *, *, allow\np, role:owner, logs, *, *, allow\np, role:owner, exec, *, *, allow\np, role:operator, applications, get, */*, allow\np, role:operator, applications, list, */*, allow\np, role:operator, applications, watch, */*, allow\np, role:operator, applications, sync, */*, allow\np, role:operator, applications, action/*, */*, allow\np, role:operator, logs, get, */*, allow\np, role:operator, applications, *, test-apps/*, allow\np, role:operator, applications, update/*, */*, allow\np, role:operator, applications, delete/*, */*, allow\np, role:viewer, applications, get, */*, allow\np, role:viewer, applications, list, */*, allow\np, role:viewer, applications, watch, */*, allow\np, role:viewer, clusters, get, *, allow\np, role:viewer, repositories, get, *, allow\np, role:viewer, projects, get, *, allow\np, role:readonly, applications, get, */*, allow\np, role:readonly, applications, list, */*, allow\n","policy.default":"role:readonly","scopes":"[groups]"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app.kubernetes.io/name":"argocd-rbac-cm","app.kubernetes.io/part-of":"argocd","argocd.version.migration":"v3.0"},"name":"argocd-rbac-cm","namespace":"argocd"}}
  creationTimestamp: "2025-12-25T10:35:46Z"
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
    argocd.version.migration: v3.0
  name: argocd-rbac-cm
  namespace: argocd
  resourceVersion: "5445"
  uid: b8cd2181-8312-46df-9765-b7f648b2cc94
