apiVersion: v1
items:
- apiVersion: v1
  kind: Secret
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Secret","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"notifications-controller","app.kubernetes.io/name":"argocd-notifications-controller","app.kubernetes.io/part-of":"argocd","argocd.version":"v2.10.17","demo.upgrade.step":"initial"},"name":"argocd-notifications-secret","namespace":"argocd"},"type":"Opaque"}
    creationTimestamp: "2025-12-24T09:41:03Z"
    labels:
      app.kubernetes.io/component: notifications-controller
      app.kubernetes.io/name: argocd-notifications-controller
      app.kubernetes.io/part-of: argocd
      argocd.version: v2.10.17
      demo.upgrade.step: initial
    name: argocd-notifications-secret
    namespace: argocd
    resourceVersion: "648"
    uid: bbcc7bae-df04-4182-b26c-bb930eafb3a9
  type: Opaque
- apiVersion: v1
  data:
    auth: M3gxdUViSTN3LVhVMXp4bg==
  kind: Secret
  metadata:
    creationTimestamp: "2025-12-24T09:41:17Z"
    name: argocd-redis
    namespace: argocd
    resourceVersion: "817"
    uid: bfa10d43-f352-4b85-b591-1bb786a1a908
  type: Opaque
- apiVersion: v1
  data:
    admin.password: JDJhJDEwJGE0T085VktCa0lUQ05PTzE3MWUxZnVOYmU4WkZzd2hjNVBGUGpBTS9tclYuRXd5MmNJYzA2
    admin.passwordMtime: MjAyNC0wMS0wMVQwMDowMDowMFo=
    server.secretkey: bWluaWt1YmUtZGVtby1zZWNyZXQta2V5LWNoYW5nZS1pbi1wcm9k
    tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURZakNDQWtxZ0F3SUJBZ0lRWlJhcFg3TmtyZzhDVnpxQ29kSnZhakFOQmdrcWhraUc5dzBCQVFzRkFEQVMKTVJBd0RnWURWUVFLRXdkQmNtZHZJRU5FTUI0WERUSTFNVEl5TkRBNU5ERXlNbG9YRFRJMk1USXlOREE1TkRFeQpNbG93RWpFUU1BNEdBMVVFQ2hNSFFYSm5ieUJEUkRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDCkFRb0NnZ0VCQUx5Nk4wQmV4OXFlbXNHbWhERElTbFVnTDJpZ0hFRkh5ZC9YZ2dDOXhmRGw3SjlqS0VwWTEwQnUKcVRxbzRTT0NHT2ZMaEtHdGRwczB6RFFBZ0F5MEpDbTFnd0xyRzFaY3c4THE3REZWSFNjSkg1NGw0alpxM3VzdApkdWVSRnZtekpaU3l0cEh1OW1zZWpja0JjVlpTUUdLRUpSTURRZm9oK1BCanpSa0tmd2Rxc2pFaU9uTUNrVmcwCjVuOEp4Qzl3QjRNSjExOFRNM2tRVUlJK0FRb0xmNDQrOUpNZmg5d2IzNkI2ckZxOTNxbWJiaE12TmxQaHRMVmgKNTJMZzdnNDBJKzN1NkNvSTUwdWFNemEvUjJpMk5pUFFFVnN2OTJHSHFCZ2xxVVBKaDllSVJqcndUbHJFWUdWUgpMUFIrdFNDeXdXakQwdUp0OGs5MWtNOERUYXZzeDhjQ0F3RUFBYU9Cc3pDQnNEQU9CZ05WSFE4QkFmOEVCQU1DCkJhQXdFd1lEVlIwbEJBd3dDZ1lJS3dZQkJRVUhBd0V3REFZRFZSMFRBUUgvQkFJd0FEQjdCZ05WSFJFRWREQnkKZ2dsc2IyTmhiR2h2YzNTQ0RXRnlaMjlqWkMxelpYSjJaWEtDRkdGeVoyOWpaQzF6WlhKMlpYSXVZWEpuYjJOawpnaGhoY21kdlkyUXRjMlZ5ZG1WeUxtRnlaMjlqWkM1emRtT0NKbUZ5WjI5alpDMXpaWEoyWlhJdVlYSm5iMk5rCkxuTjJZeTVqYkhWemRHVnlMbXh2WTJGc01BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQzVTd2lmTEkxcFY5eW4KSVhSakJRc1RWa094YStMMHJuUy91OE9URDA2NFE1SU4vQ1NrNkdZZzE3VWF0MUoySytDRG1NZkpmSHJvY1FZMApvRzVuQVZDV0xDYVdOOVN4bVJMc2lMaXUva0NSdDEyN1dOWW9JS0FEa3VLWGd0TVpsVitsMDRhYjFiZGZxSUFICnFLbkQzMjJUMnVscjZUZk9uN1RSMFpUd1BtV2JpRUtvOVp2Sll0SjB0d0E5YlBhRitaNE43R0JlL2ZHTHpsRVMKdzdOaDduKzJPWVI2MTdJKzlOVUtTUzc1L1lLRkN6RCtzWWIxMEltTXdlR3ArMkVJd0dCaGE5UE1WYUQyTHE1aQo1ZG9zN3BuQzQ4aHNmOHZJUUwvb3dZTW9jaGZUcENrd25KREtKaWsyaXo0Q21Jd1NvbEdMemlEbUtCQnVwQS91CnhnN3ViZDVaCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb2dJQkFBS0NBUUVBdkxvM1FGN0gycDZhd2FhRU1NaEtWU0F2YUtBY1FVZkozOWVDQUwzRjhPWHNuMk1vClNsalhRRzZwT3FqaEk0SVk1OHVFb2ExMm16VE1OQUNBRExRa0tiV0RBdXNiVmx6RHd1cnNNVlVkSndrZm5pWGkKTm1yZTZ5MTI1NUVXK2JNbGxMSzJrZTcyYXg2TnlRRnhWbEpBWW9RbEV3TkIraUg0OEdQTkdRcC9CMnF5TVNJNgpjd0tSV0RUbWZ3bkVMM0FIZ3duWFh4TXplUkJRZ2o0QkNndC9qajcwa3grSDNCdmZvSHFzV3IzZXFadHVFeTgyClUrRzB0V0huWXVEdURqUWo3ZTdvS2dqblM1b3pOcjlIYUxZMkk5QVJXeS8zWVllb0dDV3BROG1IMTRoR092Qk8KV3NSZ1pWRXM5SDYxSUxMQmFNUFM0bTN5VDNXUXp3Tk5xK3pIeHdJREFRQUJBb0lCQUNzTHZqWnNaK0V4YzlMZgpqQjhrVC9BQ20wMmQxMVA4YjhzaWVJQjZ5SDhkc2s3WWF3UXFKMDZHN3dwMklvUGExSnRxRENKa1VqMHNXYmN5CnRnSXZ4Ri9QQ3NiTG9UeWRnL2tkWkNvTVk4M1hndUtyZVdFNEZ3aEZJbTNHNWhxbUJkaFl1dE9tVVlZMVBkbXUKL283VnkrR3NpbGcvMGZpZmJ3eEZkeTVTK281U0h6MmtMeDVyUzk3Szh5MVFOdzFUZUJOMFdHSUhpMENNMCtXRQowelZTMEI5bndGYXJhTEZJanVTZElBUjhKR1JKRlFUMUlFU2RyazF2dzRHMkJqT1JhN3hBMzQwUmdmNmptZHA0CkhqSy92dGFOQ1pkdkljeGhBWFFMdnhRNjFnRE8rUVlrV3VxWHhVaTg0ZFpGZHRoSnBvZ0IzcElxVjI2Q0FpY0oKWEZUN2ppRUNnWUVBemNXd2hhVmdqamdNMFdsdUUyZkI4TXBzWnFnSG1wMWhPT1J3T1NkcTI0VW5SNzVsL3VMTgphNlE0WU5pVW1MeUFlN3l3aGxFZVVHcGpwai8wMkR5SDZ6cDdodVpQTWdpUm1xUlBvNzJ6L0NzUkNDM3EwVmJICjFNUTE3d0RVM0I5cnhPVS80NktzTk55WlZyRld2L1BRNVEyTzBoZUhCb1hmdVk1ZHg4b08zeXNDZ1lFQTZzdHQKcHNpb3dVSGhmVVpUTlBkejU1dldCd3A4RHhnOWdUV3FTSC9QVmZpblZTdzFlRkREekRMYlFQL3VubHVUdy81LwpzYkdOYmRTRG5ha0c4THNrTHlaMWNEdlVUYi9qcWUvR0F2b0hlVjMvVzlwdnF5ZG5qNDhzQnJacnd1RXlkcktPCm9FNndZMnk3TjlPa3IwVmw5UDFINzBGQzlwaTNtaUVCaU96Q3k5VUNnWUE5K3JtOHg1OVp0eEJGVTFoUWlBUW0KbnhJZnFhVUFzVDdEZ0NzOVM5NG4yT2VIK0pXSVBKQmJSOCtqZkJqbUdJRXF4QjczbGg5bllXUTZnekVnb0xyZgo0M0dwcEYxZVdLNWl3Zk1yQXN6ZnU2a1pxWnI5Q3dLTjE3dlhEWTBQOEhicGk1Tys0UlMxcDJ5WWJEb1EvME9BCmVxRDJMeGdBb3ZwTVRkRjVpQ2NLbVFLQmdGcXVESUJRbVJSaWZGTGt1VGdJcGVQNmhMT2RjZ0ptYTBLZTFsQS8KeEhUQW51ZS9OanRzZmVJOGRmOXBtTi9pSUhTZXN2U096VDl3eHhBNStxczRxNlhtSlk4ZUhFV1c2YmQxR2pXRwpHU0xma2NNSTN2M3NMd3Y3MEpZYkdBMWc2aHQ3cEtmM0hCcWFJTWhUM2hPdktzeHVrYnl1cU0wU2VENTNwdDhhCkNiV3RBb0dBYU9ISE44L0ZrcW5kUS82eUE3UFhRV2VJSkpHMzhhV1ZienpzRWtWejQraXUrcFcya2MzWDcvTVUKa3BuUk9sMEdSQTlleXpmaWkvZFZ5RlFNeVN4SlJOMmgvdzFQc0xGTk1qSE5RR3p4aXRCaUY1aHlnWm42dHVvNwpZaU84YWhtaS9KSk1WYmJpRVNteDl4MzY2R1pIQ25Ha2dvelpQMDFNNnFhdFpYaVNmNFE9Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
  kind: Secret
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Secret","metadata":{"annotations":{},"labels":{"app.kubernetes.io/name":"argocd-secret","app.kubernetes.io/part-of":"argocd","argocd.version":"v2.10.17","demo.upgrade.step":"initial"},"name":"argocd-secret","namespace":"argocd"},"stringData":{"admin.password":"$2a$10$a4OO9VKBkITCNOO171e1fuNbe8ZFswhc5PFPjAM/mrV.Ewy2cIc06","admin.passwordMtime":"2024-01-01T00:00:00Z","server.secretkey":"minikube-demo-secret-key-change-in-prod"},"type":"Opaque"}
    creationTimestamp: "2025-12-24T09:41:03Z"
    labels:
      app.kubernetes.io/name: argocd-secret
      app.kubernetes.io/part-of: argocd
      argocd.version: v2.10.17
      demo.upgrade.step: initial
    name: argocd-secret
    namespace: argocd
    resourceVersion: "848"
    uid: 23b85ad2-cef8-448f-9a22-ad575191d815
  type: Opaque
kind: List
metadata:
  resourceVersion: ""
