apiVersion: v1
data:
  policy.csv: |
    g, admin, role:owner
    g, operator, role:operator
    g, viewer, role:viewer

    p, role:owner, applications, *, */*, allow

    p, role:owner, clusters, *, *, allow

    p, role:owner, repositories, *, *, allow

    p, role:owner, projects, *, *, allow

    p, role:owner, accounts, *, *, allow

    p, role:owner, gpgkeys, *, *, allow

    p, role:owner, logs, *, *, allow

    p, role:owner, exec, *, *, allow

    p, role:operator, applications, get, */*, allow
    p, role:operator, applications, list, */*, allow
    p, role:operator, applications, watch, */*, allow

    p, role:operator, applications, sync, */*, allow

    p, role:operator, applications, action/*, */*, allow

    p, role:operator, logs, get, */*, allow

    p, role:operator, applications, *, test-apps/*, allow

    p, role:viewer, applications, get, */*, allow
    p, role:viewer, applications, list, */*, allow
    p, role:viewer, applications, watch, */*, allow

    p, role:viewer, clusters, get, *, allow

    p, role:viewer, repositories, get, *, allow

    p, role:viewer, projects, get, *, allow

    p, role:readonly, applications, get, */*, allow
    p, role:readonly, applications, list, */*, allow
  policy.default: role:readonly
  scopes: '[groups]'
kind: ConfigMap
metadata:
  annotations:
    argocd.version: v2.10.17
    demo.upgrade.step: initial
  creationTimestamp: "2025-12-25T10:35:46Z"
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-rbac-cm
  namespace: argocd
  resourceVersion: "611"
  uid: b8cd2181-8312-46df-9765-b7f648b2cc94
