# Disable the Job that deletes argocd-initial-admin-secret
#
# ArgoCD's default installation includes a Job that automatically deletes
# the argocd-initial-admin-secret after 30 seconds. This is a security best
# practice for production, but for demo/testing purposes, we want to keep
# the secret available.
#
# This patch removes the Job from the installation by setting replicas to 0
# (can't delete it entirely via Kustomize strategic merge).
#
# Production note: In production, you should let ArgoCD delete this secret
# and use proper secret management (Vault, AWS Secrets Manager, etc.)
#
apiVersion: batch/v1
kind: Job
metadata:
  name: argocd-initial-admin-secret-cleanup
  namespace: argocd
spec:
  # Disable the job by setting backoffLimit to 0 and making it fail immediately
  # We can't remove the job entirely with Kustomize, so we neuter it instead
  backoffLimit: 0
  ttlSecondsAfterFinished: 0
  template:
    spec:
      containers:
      - name: cleanup
        # Use a command that does nothing and exits successfully
        command: ["/bin/sh", "-c", "echo 'Secret cleanup disabled for demo purposes'; exit 0"]
        # Override the entire container to prevent deletion
        image: alpine:3.18
      restartPolicy: Never
