# Argo CD Secret - Local Admin Credentials
#
# PRODUCTION VS MINIKUBE:
# ┌─────────────────────────────────┬──────────────────────────────────────────┐
# │ Production                      │ Minikube                                 │
# ├─────────────────────────────────┼──────────────────────────────────────────┤
# │ Uses ExternalSecrets with AWS   │ Plain Kubernetes Secret                  │
# │ GitHub webhook secrets          │ Not needed (no webhooks)                 │
# │ New Relic API key               │ Not needed (no monitoring)               │
# │ Admin account disabled          │ Admin account enabled                    │
# └─────────────────────────────────┴──────────────────────────────────────────┘
#
# Production setup (for reference):
# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# spec:
#   secretStoreRef:
#     kind: ClusterSecretStore
#     name: aws-secretsmanager
#   target:
#     name: argocd-secret
#     creationPolicy: Merge
#   data:
#     - secretKey: webhook.github.secret
#       remoteRef:
#         key: eks/hub/sunflower-hub-eks/argocd/external-secret
#         property: argocd.webhook.github.secret
#
# For minikube, we create a simple secret with the admin password.
# The password is 'admin123' - suitable for local testing only.
#
# NOTE: Argo CD generates an initial admin secret on first install.
# This secret is optional - if you don't provide it, Argo CD will create one.
# We include it here for consistency and to show what would be needed in production.
#
apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
type: Opaque
stringData:
  # Admin password for local testing
  # IMPORTANT: This must be a bcrypt hash that ArgoCD can verify against.
  # Generated with: htpasswd -nbBC 10 "" admin123 | tr -d ':\n' | sed 's/$2y/$2a/'
  # Plain text password: admin123
  #
  # NOTE: In production, this is not set because admin is disabled (SSO only).
  # For minikube testing, we enable admin and set a known password.
  #
  # The bcrypt hash below corresponds to password: admin123
  admin.password: "$2a$10$a4OO9VKBkITCNOO171e1fuNbe8ZFswhc5PFPjAM/mrV.Ewy2cIc06"

  # Store plaintext password for initial admin secret (will be created by ArgoCD)
  # This gets used by ArgoCD to create argocd-initial-admin-secret
  admin.passwordMtime: "2024-01-01T00:00:00Z"

  # Server secret key (used for session tokens)
  # This should be a random string. Using a fixed value for demo reproducibility.
  server.secretkey: "minikube-demo-secret-key-change-in-prod"

  # ===========================================================================
  # PRODUCTION SECRETS (not needed for minikube)
  # ===========================================================================
  # These would be present in production via ExternalSecrets:
  #
  # webhook.github.secret: <from AWS Secrets Manager>
  #   Used to verify GitHub webhook payloads
  #
  # newrelic.apikey: <from AWS Secrets Manager>
  #   Used for deployment notifications to New Relic
  #
  # For minikube, we don't need webhooks or external notifications.
